{% set version = "0.16.3" %}

package:
  name: datashader
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/datashader/datashader-{{ version }}.tar.gz
  sha256: 9d0040c7887f7a5a5edd374c297402fd208a62bf6845e87631b54f03b9ae479d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - datashader = datashader.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - param
    - pyct-core
  run:
    - python >={{ python_min }}
    - colorcet
    - dask-core
    - multipledispatch
    - numba
    - numpy
    - packaging
    - pandas
    - param
    - pillow
    - pyct
    - requests
    - scipy
    - toolz
    - xarray

test:
  requires:
    - fastparquet
    - flake8
    - nbsmoke >=0.5.0
    - pytest
    - pytest-benchmark
    - holoviews >=1.14.1
    - netcdf4
    - python {{ python_min }}
  imports:
    - datashader
  commands:
    - datashader copy-examples --path=. --force
    # just run one notebook for now; increase in the future if notebooks can be run quickly with test/tiny data
    - pytest --nbsmoke-run -k ".ipynb" getting_started/2_Pipeline.ipynb

about:
  home: https://datashader.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Data visualization toolchain based on aggregating into a grid
  description: |
    Datashader is a data rasterization pipeline for automating the process of
    creating meaningful representations of large amounts of data.
  doc_url: https://datashader.org
  dev_url: https://github.com/holoviz/datashader

extra:
  recipe-maintainers:
    - maximlt
    - jbednar
    - ocefpaf
    - philippjfr
    - hoxbro
